//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentationAnalyzers.RefactoringRules {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RefactoringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RefactoringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentationAnalyzers.RefactoringRules.RefactoringResources", typeof(RefactoringResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render documentation as Markdown.
        /// </summary>
        internal static string DOC900CodeFix {
            get {
                return ResourceManager.GetString("DOC900CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render documentation as Markdown (Refactoring).
        /// </summary>
        internal static string DOC900Description {
            get {
                return ResourceManager.GetString("DOC900Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render documentation as Markdown.
        /// </summary>
        internal static string DOC900MessageFormat {
            get {
                return ResourceManager.GetString("DOC900MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render documentation as Markdown (Refactoring).
        /// </summary>
        internal static string DOC900Title {
            get {
                return ResourceManager.GetString("DOC900Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to documentation comment.
        /// </summary>
        internal static string DOC901CodeFix {
            get {
                return ResourceManager.GetString("DOC901CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to documentation comment.
        /// </summary>
        internal static string DOC901Description {
            get {
                return ResourceManager.GetString("DOC901Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to documentation comment.
        /// </summary>
        internal static string DOC901MessageFormat {
            get {
                return ResourceManager.GetString("DOC901MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to documentation comment.
        /// </summary>
        internal static string DOC901Title {
            get {
                return ResourceManager.GetString("DOC901Title", resourceCulture);
            }
        }
    }
}
