//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentationAnalyzers.PortabilityRules {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PortabilityResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PortabilityResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentationAnalyzers.PortabilityRules.PortabilityResources", typeof(PortabilityResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use XML documentation syntax.
        /// </summary>
        internal static string DOC200CodeFix {
            get {
                return ResourceManager.GetString("DOC200CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use XML documentation syntax.
        /// </summary>
        internal static string DOC200Description {
            get {
                return ResourceManager.GetString("DOC200Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use XML documentation syntax.
        /// </summary>
        internal static string DOC200MessageFormat {
            get {
                return ResourceManager.GetString("DOC200MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use XML documentation syntax.
        /// </summary>
        internal static string DOC200Title {
            get {
                return ResourceManager.GetString("DOC200Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item should have description.
        /// </summary>
        internal static string DOC201CodeFix {
            get {
                return ResourceManager.GetString("DOC201CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item should have description.
        /// </summary>
        internal static string DOC201Description {
            get {
                return ResourceManager.GetString("DOC201Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item should have description.
        /// </summary>
        internal static string DOC201MessageFormat {
            get {
                return ResourceManager.GetString("DOC201MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item should have description.
        /// </summary>
        internal static string DOC201Title {
            get {
                return ResourceManager.GetString("DOC201Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to expected element.
        /// </summary>
        internal static string DOC202CodeFix {
            get {
                return ResourceManager.GetString("DOC202CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use section elements correctly.
        /// </summary>
        internal static string DOC202Description {
            get {
                return ResourceManager.GetString("DOC202Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use section elements correctly.
        /// </summary>
        internal static string DOC202MessageFormat {
            get {
                return ResourceManager.GetString("DOC202MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use section elements correctly.
        /// </summary>
        internal static string DOC202Title {
            get {
                return ResourceManager.GetString("DOC202Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to expected element.
        /// </summary>
        internal static string DOC203CodeFix {
            get {
                return ResourceManager.GetString("DOC203CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use block elements correctly.
        /// </summary>
        internal static string DOC203Description {
            get {
                return ResourceManager.GetString("DOC203Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use block elements correctly.
        /// </summary>
        internal static string DOC203MessageFormat {
            get {
                return ResourceManager.GetString("DOC203MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use block elements correctly.
        /// </summary>
        internal static string DOC203Title {
            get {
                return ResourceManager.GetString("DOC203Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to expected element.
        /// </summary>
        internal static string DOC204CodeFix {
            get {
                return ResourceManager.GetString("DOC204CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use inline elements correctly.
        /// </summary>
        internal static string DOC204Description {
            get {
                return ResourceManager.GetString("DOC204Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use inline elements correctly.
        /// </summary>
        internal static string DOC204MessageFormat {
            get {
                return ResourceManager.GetString("DOC204MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use inline elements correctly.
        /// </summary>
        internal static string DOC204Title {
            get {
                return ResourceManager.GetString("DOC204Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;see langword&apos; correctly.
        /// </summary>
        internal static string DOC207Description {
            get {
                return ResourceManager.GetString("DOC207Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;see langword&apos; correctly.
        /// </summary>
        internal static string DOC207MessageFormat {
            get {
                return ResourceManager.GetString("DOC207MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;see langword&apos; correctly.
        /// </summary>
        internal static string DOC207Title {
            get {
                return ResourceManager.GetString("DOC207Title", resourceCulture);
            }
        }
    }
}
