//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentationAnalyzers.StyleRules {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StyleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StyleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentationAnalyzers.StyleRules.StyleResources", typeof(StyleResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert paragraph element.
        /// </summary>
        internal static string BlockLevelDocumentationCodeFix {
            get {
                return ResourceManager.GetString("BlockLevelDocumentationCodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The documentation for the element contains text which is not placed in paragraphs..
        /// </summary>
        internal static string DOC100Description {
            get {
                return ResourceManager.GetString("DOC100Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place text in paragraphs.
        /// </summary>
        internal static string DOC100MessageFormat {
            get {
                return ResourceManager.GetString("DOC100MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place text in paragraphs.
        /// </summary>
        internal static string DOC100Title {
            get {
                return ResourceManager.GetString("DOC100Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The documentation for the element contains some text which is wrapped in block-level elements, and other text which is written inline..
        /// </summary>
        internal static string DOC101Description {
            get {
                return ResourceManager.GetString("DOC101Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use child blocks consistently.
        /// </summary>
        internal static string DOC101MessageFormat {
            get {
                return ResourceManager.GetString("DOC101MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use child blocks consistently.
        /// </summary>
        internal static string DOC101Title {
            get {
                return ResourceManager.GetString("DOC101Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The documentation for the element contains inline text, but the documentation for a sibling element of the same kind uses block-level elements..
        /// </summary>
        internal static string DOC102Description {
            get {
                return ResourceManager.GetString("DOC102Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use child blocks consistently across elements of the same kind.
        /// </summary>
        internal static string DOC102MessageFormat {
            get {
                return ResourceManager.GetString("DOC102MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use child blocks consistently across elements of the same kind.
        /// </summary>
        internal static string DOC102Title {
            get {
                return ResourceManager.GetString("DOC102Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Unicode characters.
        /// </summary>
        internal static string DOC103CodeFix {
            get {
                return ResourceManager.GetString("DOC103CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Unicode characters.
        /// </summary>
        internal static string DOC103Description {
            get {
                return ResourceManager.GetString("DOC103Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Unicode characters.
        /// </summary>
        internal static string DOC103MessageFormat {
            get {
                return ResourceManager.GetString("DOC103MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Unicode characters.
        /// </summary>
        internal static string DOC103Title {
            get {
                return ResourceManager.GetString("DOC103Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;see langword&apos;.
        /// </summary>
        internal static string DOC104CodeFix {
            get {
                return ResourceManager.GetString("DOC104CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer &apos;&lt;see langword=&quot;keyword&quot;/&gt;&apos; to &apos;&lt;c&gt;keyword&lt;/c&gt;&apos; for referencing language keywords.
        /// </summary>
        internal static string DOC104Description {
            get {
                return ResourceManager.GetString("DOC104Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer &apos;&lt;see langword=&quot;keyword&quot;/&gt;&apos; to &apos;&lt;c&gt;keyword&lt;/c&gt;&apos; for referencing language keywords.
        /// </summary>
        internal static string DOC104MessageFormat {
            get {
                return ResourceManager.GetString("DOC104MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;see langword&apos;.
        /// </summary>
        internal static string DOC104Title {
            get {
                return ResourceManager.GetString("DOC104Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;paramref&apos;.
        /// </summary>
        internal static string DOC105CodeFix {
            get {
                return ResourceManager.GetString("DOC105CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer &apos;&lt;paramref name=&quot;parameter&quot;/&gt;&apos; to &apos;&lt;c&gt;parameter&lt;/c&gt;&apos; for referencing parameters.
        /// </summary>
        internal static string DOC105Description {
            get {
                return ResourceManager.GetString("DOC105Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer &apos;&lt;paramref name=&quot;parameter&quot;/&gt;&apos; to &apos;&lt;c&gt;parameter&lt;/c&gt;&apos; for referencing parameters.
        /// </summary>
        internal static string DOC105MessageFormat {
            get {
                return ResourceManager.GetString("DOC105MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;paramref&apos;.
        /// </summary>
        internal static string DOC105Title {
            get {
                return ResourceManager.GetString("DOC105Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;typeparamref&apos;.
        /// </summary>
        internal static string DOC106CodeFix {
            get {
                return ResourceManager.GetString("DOC106CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer &apos;&lt;typeparamref name=&quot;type_parameter&quot;/&gt;&apos; to &apos;&lt;c&gt;type_parameter&lt;/c&gt;&apos; for referencing type parameters.
        /// </summary>
        internal static string DOC106Description {
            get {
                return ResourceManager.GetString("DOC106Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer &apos;&lt;typeparamref name=&quot;type_parameter&quot;/&gt;&apos; to &apos;&lt;c&gt;type_parameter&lt;/c&gt;&apos; for referencing type parameters.
        /// </summary>
        internal static string DOC106MessageFormat {
            get {
                return ResourceManager.GetString("DOC106MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;typeparamref&apos;.
        /// </summary>
        internal static string DOC106Title {
            get {
                return ResourceManager.GetString("DOC106Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;see cref&apos;.
        /// </summary>
        internal static string DOC107CodeFix {
            get {
                return ResourceManager.GetString("DOC107CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer &apos;&lt;see cref=&quot;target&quot;/&gt;&apos; to &apos;&lt;c&gt;target&lt;/c&gt;&apos; for referencing code elements.
        /// </summary>
        internal static string DOC107Description {
            get {
                return ResourceManager.GetString("DOC107Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer &apos;&lt;see cref=&quot;target&quot;/&gt;&apos; to &apos;&lt;c&gt;target&lt;/c&gt;&apos; for referencing code elements.
        /// </summary>
        internal static string DOC107MessageFormat {
            get {
                return ResourceManager.GetString("DOC107MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;see cref&apos;.
        /// </summary>
        internal static string DOC107Title {
            get {
                return ResourceManager.GetString("DOC107Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap text in paragraph element.
        /// </summary>
        internal static string DOC108CodeFix {
            get {
                return ResourceManager.GetString("DOC108CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid empty paragraphs.
        /// </summary>
        internal static string DOC108Description {
            get {
                return ResourceManager.GetString("DOC108Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid empty paragraphs.
        /// </summary>
        internal static string DOC108MessageFormat {
            get {
                return ResourceManager.GetString("DOC108MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid empty paragraphs.
        /// </summary>
        internal static string DOC108Title {
            get {
                return ResourceManager.GetString("DOC108Title", resourceCulture);
            }
        }
    }
}
